apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm
  contents:
  - path: keda
    git:
      url: https://github.com/giantswarm/keda-upstream
      ref: main
      depth: 1
    newRootPath: keda
    ignorePaths:
    - .kube-linter.yaml
    - values.schema.json