apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm
  contents:
  - path: keda
    git:
      url: https://github.com/giantswarm/keda-upstream
      ## We get version 2.10.2 because of kubernetes compatibily reasons
      ref: v2.10.2
      depth: 1
    newRootPath: keda
    ignorePaths:
    - .kube-linter.yaml
    - values.schema.json
