apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm
  contents:
  - path: keda
    git:
      url: https://github.com/giantswarm/keda-upstream
      ## We use version 2.18.x because of kubernetes compatibility reasons
      ref: release/v2.18
      depth: 1
    newRootPath: keda
    ignorePaths:
    - .kube-linter.yaml
    - values.schema.json
